### ISSUE TITLE
Add new paper "DeTiME: Diffusion-Enhanced Topic Modeling using Encoder-decoder based LLM"

### ISSUE THREAD

**Issue by personalization-trap** [AoiDragon/Awesome-Text-Diffusion-Models#1]
Hi,

Thanks for your wonderful survey!
Would you mind adding our paper published in EMNLP 2023? It leverages diffusion for topic guided text generation. It leverages a continuous diffusion model to do topic guided text generation. 
Title: DeTiME: Diffusion-Enhanced Topic Modeling using Encoder-decoder based LLM
Paper link: https://arxiv.org/abs/2310.15296

**Comment by AoiDragon** [comment]
Sure, thanks for the reminder.

**Comment by personalization-trap** [comment]
Thank you so much!
